-- =========================================
-- E-COMMERCE DATA ANALYSIS
-- =========================================
-- Total revenue
-- Calculating total revenue generated from all orders
SELECT SUM(p.price*oi.quantity) AS total_revenue
FROM order_items AS oi
JOIN products AS p ON oi.product_id = p.product_id;
-- =========================================
-- Monthly revenue
-- Shows how revenue changed each month
SELECT 
	strftime('%Y-%m', o.order_date) as month, 
	SUM (p.price*oi.quantity) as revenue
FROM orders AS o
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON oi.product_id = p.product_id
GROUP BY month
ORDER BY month;
-- =========================================
-- Top 10 clients
-- Identifying 10 clients generating the highest revenue
SELECT c.customer_id, 
	c.name, 
	SUM(p.price*oi.quantity) as revenue
FROM customers AS c
JOIN orders AS o ON c.customer_id = o.customer_id
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.name
ORDER BY revenue DESC 
LIMIT 10;
-- =========================================
-- Average revenue per order
-- Calculating average revenue generated by a single order
SELECT AVG (order_total) FROM (
	SELECT o.order_id, SUM(p.price * oi.quantity) as order_total
	FROM orders o
	JOIN order_items AS oi ON o.order_id = oi.order_id
	JOIN products AS p ON oi.product_id = p.product_id
	GROUP BY o.order_id);
-- =========================================
-- Categories popularity
-- Finding out popularity of each category
SELECT  p.category, 
	SUM(p.price*oi.quantity) as revenue
FROM products AS p
JOIN order_items AS oi ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC;
-- =========================================
-- Top 10 products
-- Identifying 10 most selling products
SELECT  p.product_id, 
	SUM(p.price*oi.quantity) as revenue
FROM products AS p
JOIN order_items AS oi ON p.product_id = oi.product_id
GROUP BY p.product_id
ORDER BY revenue DESC
LIMIT 10;

